import { v } from "convex/values";
import { internalMutation } from "./_generated/server";
import { api } from "./_generated/api";
import { Doc, Id } from "./_generated/dataModel";

// One-off "fresh start" for the October 2026 replan (cups on three shelves).
// Run with dryRun: true first; it returns every change it would make and
// writes nothing. Re-running with dryRun: false is idempotent: cups already in
// their target shape are left as they are.

type CupTarget = {
  from: string[]; // current bucket names that become this cup (first active match wins)
  name: string;
  group: string;
  mode: "spend" | "recurring";
  planned: number;
  opening: number; // carryoverBalance to start October with
};

const CUPS: CupTarget[] = [
  // Everyday
  { from: ["Food"], name: "Food", group: "Everyday", mode: "spend", planned: 270, opening: 0 },
  { from: ["Grocery"], name: "Grocery", group: "Everyday", mode: "spend", planned: 30, opening: 0 },
  { from: ["Transport"], name: "Transport", group: "Everyday", mode: "spend", planned: 100, opening: 0 },
  { from: ["maintenance", "Maintenance"], name: "Maintenance", group: "Everyday", mode: "spend", planned: 50, opening: 0 },
  // For me
  { from: ["Self care"], name: "Self care", group: "For me", mode: "spend", planned: 300, opening: 0 },
  { from: ["Fitness"], name: "Fitness", group: "For me", mode: "spend", planned: 100, opening: 560 },
  { from: ["Shopping"], name: "Shopping", group: "For me", mode: "spend", planned: 150, opening: 0 },
  { from: ["Entertainment"], name: "Entertainment", group: "For me", mode: "spend", planned: 50, opening: 0 },
  // Saving up
  { from: ["Travel", "Adventures"], name: "Adventures", group: "Saving up", mode: "spend", planned: 500, opening: 0 },
  { from: ["Family trips"], name: "Family trips", group: "Saving up", mode: "spend", planned: 0, opening: 4500 },
  { from: ["gifts", "Gifts"], name: "Gifts", group: "Saving up", mode: "spend", planned: 200, opening: 1100 },
  { from: ["Home decor"], name: "Home decor", group: "Saving up", mode: "spend", planned: 50, opening: 0 },
  { from: ["Enrichment"], name: "Enrichment", group: "Saving up", mode: "spend", planned: 100, opening: 0 },
  // Fixed (paid automatically each month, never shown as cups)
  { from: ["shared acc", "Shared account"], name: "Shared account", group: "Fixed", mode: "recurring", planned: 1100, opening: 0 },
  { from: ["Asian tax", "Parents"], name: "Parents", group: "Fixed", mode: "recurring", planned: 600, opening: 0 },
  { from: ["taxes", "Tax"], name: "Tax", group: "Fixed", mode: "recurring", planned: 450.51, opening: 0 },
  { from: ["insurance", "Insurance"], name: "Insurance", group: "Fixed", mode: "recurring", planned: 280, opening: 0 },
  // Investing
  { from: ["AIA Pro Achiever"], name: "AIA Pro Achiever", group: "Investments", mode: "recurring", planned: 208, opening: 0 },
  { from: ["endowus", "Endowus"], name: "Endowus", group: "Investments", mode: "recurring", planned: 0, opening: 0 },
  { from: ["investments - ibkr", "IBKR"], name: "IBKR", group: "Investments", mode: "recurring", planned: 0, opening: 0 },
];

const RETIRE = ["Dates"];
const GROUP_ORDER = ["Everyday", "For me", "Saving up", "Goals", "Fixed", "Investments"];
const GROUP_RENAMES: Record<string, string> = {
  "Necessary evils": "Fixed",
  "Self care": "For me",
  "Personal growth": "Saving up",
};

export const run = internalMutation({
  args: {
    userId: v.id("users"),
    dryRun: v.boolean(),
    octoberIncome: v.number(), // the 30 Sep salary, funding October
  },
  handler: async (ctx, { userId, dryRun, octoberIncome }) => {
    const log: string[] = [];
    const now = Date.now();
    const say = (s: string) => log.push(s);

    const all = await ctx.db
      .query("buckets")
      .withIndex("by_user", (q) => q.eq("userId", userId))
      .collect();
    const active = all.filter((b) => b.isActive);

    // 1. Retire buckets that are no longer used (their auto-generated rows go too).
    for (const name of RETIRE) {
      for (const b of active.filter((x) => x.name === name)) {
        const exps = await ctx.db
          .query("expenses")
          .withIndex("by_bucket", (q) => q.eq("bucketId", b._id))
          .collect();
        const fake = exps.filter((e) => e.isAutoGenerated);
        say(`retire "${b.name}" (${exps.length} expenses; deleting ${fake.length} auto-generated: ${fake.map((e) => "$" + e.amount).join(", ") || "none"})`);
        if (!dryRun) {
          for (const e of fake) await ctx.db.delete(e._id);
          await ctx.db.patch(b._id, { isActive: false });
        }
      }
    }

    // 2. Hard-delete inactive buckets that never held an expense (duplicates).
    for (const b of all.filter((x) => !x.isActive)) {
      const one = await ctx.db
        .query("expenses")
        .withIndex("by_bucket", (q) => q.eq("bucketId", b._id))
        .first();
      if (one) {
        say(`keep inactive "${b.name}" (has history)`);
        continue;
      }
      say(`delete inactive duplicate "${b.name}"`);
      if (!dryRun) await ctx.db.delete(b._id);
    }

    // 3. Groups: rename old ones, create missing ones, set order.
    const groups = await ctx.db
      .query("groups")
      .withIndex("by_user", (q) => q.eq("userId", userId))
      .collect();
    const groupId: Record<string, Id<"groups">> = {};
    for (const g of groups) {
      const target = GROUP_RENAMES[g.name] ?? g.name;
      if (target !== g.name) say(`rename group "${g.name}" -> "${target}"`);
      if (!dryRun && target !== g.name) await ctx.db.patch(g._id, { name: target });
      groupId[target] = g._id;
    }
    for (const [i, name] of GROUP_ORDER.entries()) {
      if (!groupId[name]) {
        say(`create group "${name}"`);
        if (!dryRun) {
          groupId[name] = await ctx.db.insert("groups", { userId, name, order: i, createdAt: now });
        }
      } else if (!dryRun) {
        await ctx.db.patch(groupId[name], { order: i });
      }
    }

    // 4. Cups and fixed items.
    const used = new Set<Id<"buckets">>();
    for (const c of CUPS) {
      const b = active.find((x) => c.from.includes(x.name) && !used.has(x._id) && !RETIRE.includes(x.name));
      const fields: Partial<Doc<"buckets">> = {
        name: c.name,
        bucketMode: c.mode,
        allocationType: "amount",
        plannedAmount: c.planned,
        plannedPercent: undefined,
        allocationValue: undefined,
        carryoverBalance: c.opening,
        groupId: groupId[c.group],
      };
      if (b) {
        used.add(b._id);
        const was = `${b.name}: ${b.bucketMode}, ${b.allocationType === "percentage" ? (b.plannedPercent ?? 0) + "%" : "$" + (b.plannedAmount ?? 0)}, carry $${Math.round(b.carryoverBalance ?? 0)}`;
        say(`cup "${c.name}" [${c.group}]  was ${was}  ->  $${c.planned}/month, starts with $${c.opening}`);
        if (!dryRun) await ctx.db.patch(b._id, fields);
      } else {
        say(`NEW cup "${c.name}" [${c.group}]  $${c.planned}/month, starts with $${c.opening}`);
        if (!dryRun) {
          await ctx.db.insert("buckets", {
            userId,
            name: c.name,
            bucketMode: c.mode,
            allocationType: "amount",
            plannedAmount: c.planned,
            carryoverBalance: c.opening,
            fundedAmount: 0,
            lastRolloverDate: now,
            alertThreshold: 20,
            color: "#5C8A7A",
            groupId: groupId[c.group] ?? undefined,
            createdAt: now,
            isActive: true,
          });
        }
      }
    }

    // 5. Goals: emergency fund (already full) and reno (starts at $0, $1,860/month).
    const emergency = active.find((b) => b.bucketMode === "save" && /emergency/i.test(b.name));
    if (emergency) {
      say(`goal "Emergency fund": target $36,000, marked full, no monthly contribution`);
      if (!dryRun) {
        await ctx.db.patch(emergency._id, {
          name: "Emergency fund",
          targetAmount: 36000,
          currentBalance: 36000,
          contributionType: "none",
          contributionPercent: undefined,
          groupId: groupId["Goals"],
        });
      }
    }
    const reno = active.find((b) => b.bucketMode === "save" && /reno/i.test(b.name));
    if (!reno) {
      say(`NEW goal "Reno": target $50,000 by Sep 2027, $1,860/month, starts at $0`);
      if (!dryRun) {
        await ctx.db.insert("buckets", {
          userId,
          name: "Reno",
          bucketMode: "save",
          targetAmount: 50000,
          currentBalance: 0,
          contributionType: "amount",
          contributionAmount: 1860,
          capBehavior: "stop",
          alertThreshold: 20,
          color: "#A0785C",
          groupId: groupId["Goals"] ?? undefined,
          createdAt: now,
          isActive: true,
        });
      }
    }

    // Anything active we did not map is left alone but reported.
    for (const b of active) {
      if (used.has(b._id) || RETIRE.includes(b.name) || b === emergency || b === reno) continue;
      say(`UNMAPPED, left as is: "${b.name}" (${b.bucketMode})`);
    }

    // 6. October income: replace the misread "Received from OCBC" rows with the salary.
    const month = "2026-10";
    const rows = await ctx.db
      .query("monthlyIncome")
      .withIndex("by_user_month", (q) => q.eq("userId", userId).eq("month", month))
      .collect();
    for (const r of rows) {
      say(`remove October income row $${r.amount} "${r.note ?? ""}" (a transfer out, misread as income)`);
      if (!dryRun) await ctx.db.delete(r._id);
    }
    say(`add October income $${octoberIncome} "Salary (paid 30 Sep)"`);
    if (!dryRun) {
      await ctx.db.insert("monthlyIncome", {
        userId,
        month,
        amount: octoberIncome,
        note: "Salary (paid 30 Sep)",
        isConfirmed: true,
        confirmedAt: now,
      });
      await ctx.runMutation(api.distribution.calculateDistribution, { userId });
    }

    return { dryRun, changes: log };
  },
});
