/**
 * Reconciles the auto-generated `expenses` rows for recurring buckets to
 * match the target state defined by `computeRecurringAmount`.
 *
 * Idempotent: target state is always re-derived from current bucket /
 * income data. Re-running is a no-op once everything is in sync.
 *
 * Triggers (any one calls this — they don't need to coordinate):
 *  - Monthly rollover cron on the 1st (current month).
 *  - `buckets.update` whenever a bucket's mode/plan changes (current month).
 *  - `monthlyIncome` mutations (the affected month).
 *  - App load on the overview (current month) — self-heals cron failures
 *    and out-of-band edits.
 */

import { v } from 'convex/values';
import { mutation } from './_generated/server';
import {
  computeRecurringAmount,
  monthKey,
  monthRange,
  type ComputeReason,
} from './lib/recurring';

type SyncDiffEntry = {
  bucketId: string;
  bucketName: string;
  action: 'created' | 'updated' | 'deleted' | 'unchanged' | 'skipped';
  amount: number;
  reason: ComputeReason | 'no-change';
  expenseId?: string;
};

export const syncRecurringExpensesForMonth = mutation({
  args: {
    userId: v.id('users'),
    // "YYYY-MM" — the calendar month to reconcile. Required (don't default to
    // "today" so callers can backfill or fix specific months explicitly).
    month: v.string(),
  },
  handler: async (ctx, args): Promise<{
    month: string;
    diff: SyncDiffEntry[];
  }> => {
    // 1. Load the inputs in three indexed reads.
    const buckets = await ctx.db
      .query('buckets')
      .withIndex('by_user', q => q.eq('userId', args.userId))
      .collect();

    const monthlyEntries = await ctx.db
      .query('monthlyIncome')
      .withIndex('by_user_month', q =>
        q.eq('userId', args.userId).eq('month', args.month)
      )
      .collect();
    const totalIncome = monthlyEntries.reduce((sum, e) => sum + e.amount, 0);

    // 2. Derive the target state and reconcile per bucket.
    const diff: SyncDiffEntry[] = [];
    const recurringMonthMs = monthFromKey(args.month);

    for (const bucket of buckets) {
      // Find this bucket's existing auto-pay for this month, if any. The
      // index keyed on (bucketId, autoGeneratedForMonth) is the fast path
      // for new rows. We also pull all auto-generated rows for the bucket so
      // we catch legacy rows from before the field existed (they have
      // autoGeneratedForMonth === undefined). Legacy rows get backfilled
      // opportunistically — after the first sync touches them, the index is
      // authoritative.
      const allAutoForBucket = await ctx.db
        .query('expenses')
        .withIndex('by_bucket', q => q.eq('bucketId', bucket._id))
        .filter(q => q.eq(q.field('isAutoGenerated'), true))
        .collect();

      const existing: typeof allAutoForBucket = [];
      for (const row of allAutoForBucket) {
        if (row.autoGeneratedForMonth === args.month) {
          existing.push(row);
          continue;
        }
        if (row.autoGeneratedForMonth === undefined) {
          // Legacy row — derive its month from `date` and backfill.
          const legacyMonth = monthKey(row.date);
          await ctx.db.patch(row._id, { autoGeneratedForMonth: legacyMonth });
          if (legacyMonth === args.month) {
            existing.push({ ...row, autoGeneratedForMonth: legacyMonth });
          }
        }
      }

      // For active recurring buckets we want exactly one auto-pay; everything
      // else we want zero. Compute target first, then reconcile.
      const isTargetActive =
        bucket.isActive !== false && bucket.bucketMode === 'recurring';

      const result = computeRecurringAmount(
        // Cast through `any` because the Convex Doc type carries extra
        // metadata (_id, _creationTime, …) that the structural type ignores.
        bucket as any,
        buckets as any,
        totalIncome,
      );

      // Split out user-overridden rows — sync never touches them, but we
      // still treat them as "the payment exists for this month" so we don't
      // double up.
      const userManaged = existing.filter(r => r.userOverridden);
      const syncManaged = existing.filter(r => !r.userOverridden);

      // Should-not-exist: delete any leftover sync-managed auto-pays. Leave
      // user-overridden rows alone — even if the bucket flipped away from
      // recurring, the user might want to keep their payment record.
      if (!isTargetActive || result.amount <= 0) {
        for (const row of syncManaged) {
          await ctx.db.delete(row._id);
          diff.push({
            bucketId: bucket._id,
            bucketName: bucket.name,
            action: 'deleted',
            amount: 0,
            reason: result.reason,
            expenseId: row._id,
          });
        }
        if (syncManaged.length === 0) {
          diff.push({
            bucketId: bucket._id,
            bucketName: bucket.name,
            action: 'skipped',
            amount: 0,
            reason: result.reason,
          });
        }
        continue;
      }

      const targetAmount = roundCents(result.amount);

      // If the user already has a row (overridden), don't create a duplicate.
      if (userManaged.length > 0) {
        diff.push({
          bucketId: bucket._id,
          bucketName: bucket.name,
          action: 'skipped',
          amount: userManaged[0].amount,
          reason: 'paid',
          expenseId: userManaged[0]._id,
        });
        // Still drop sync-managed duplicates if any snuck in alongside.
        for (const row of syncManaged) {
          await ctx.db.delete(row._id);
          diff.push({
            bucketId: bucket._id,
            bucketName: bucket.name,
            action: 'deleted',
            amount: 0,
            reason: 'paid',
            expenseId: row._id,
          });
        }
        continue;
      }

      if (syncManaged.length === 0) {
        const expenseId = await ctx.db.insert('expenses', {
          userId: args.userId,
          bucketId: bucket._id,
          amount: targetAmount,
          date: recurringMonthMs,
          note: `Automatic recurring payment - ${bucket.name}`,
          isAutoGenerated: true,
          autoGeneratedForMonth: args.month,
          happinessRating: 3,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        });
        diff.push({
          bucketId: bucket._id,
          bucketName: bucket.name,
          action: 'created',
          amount: targetAmount,
          reason: result.reason,
          expenseId,
        });
        continue;
      }

      // Keep one canonical row; drop any extras (defensive).
      const [keeper, ...extras] = syncManaged;
      for (const dup of extras) {
        await ctx.db.delete(dup._id);
        diff.push({
          bucketId: bucket._id,
          bucketName: bucket.name,
          action: 'deleted',
          amount: 0,
          reason: result.reason,
          expenseId: dup._id,
        });
      }

      if (Math.abs(keeper.amount - targetAmount) > 0.005) {
        await ctx.db.patch(keeper._id, {
          amount: targetAmount,
          note: `Automatic recurring payment - ${bucket.name}`,
          updatedAt: Date.now(),
        });
        diff.push({
          bucketId: bucket._id,
          bucketName: bucket.name,
          action: 'updated',
          amount: targetAmount,
          reason: result.reason,
          expenseId: keeper._id,
        });
      } else {
        diff.push({
          bucketId: bucket._id,
          bucketName: bucket.name,
          action: 'unchanged',
          amount: targetAmount,
          reason: result.reason,
          expenseId: keeper._id,
        });
      }
    }

    return { month: args.month, diff };
  },
});

/**
 * Backfill `autoGeneratedForMonth` on legacy auto-generated rows. One-shot
 * data migration so the new dedup index has a value to key on for rows
 * created before this field existed. Idempotent — only patches rows where
 * the field is missing.
 */
export const backfillAutoGeneratedMonth = mutation({
  args: { userId: v.id('users') },
  handler: async (ctx, args): Promise<{ patched: number }> => {
    const expenses = await ctx.db
      .query('expenses')
      .withIndex('by_user', q => q.eq('userId', args.userId))
      .collect();

    let patched = 0;
    for (const expense of expenses) {
      if (!expense.isAutoGenerated) continue;
      if (expense.autoGeneratedForMonth) continue;
      await ctx.db.patch(expense._id, {
        autoGeneratedForMonth: monthKey(expense.date),
      });
      patched++;
    }
    return { patched };
  },
});

// Helpers ─────────────────────────────────────────────────────────────────

function monthFromKey(key: string): number {
  // Generated rows get `date` set to the 1st of the represented month at
  // local midnight. Using a stable date keeps month-grouping queries simple.
  const [yearStr, monthStr] = key.split('-');
  const year = parseInt(yearStr, 10);
  const month = parseInt(monthStr, 10) - 1;
  return new Date(year, month, 1, 12, 0, 0, 0).getTime();
}

function roundCents(n: number): number {
  return Math.round(n * 100) / 100;
}
