/**
 * One-time cleanup: remove the auto-generated "recurring payment" expense rows.
 *
 * Recurring buckets used to synthesize a payment each month equal to their
 * allocation, which (a) zeroed out any accumulation so they could never act as
 * a sinking fund, and (b) collided with the real bank-imported payment, which
 * is the whole "possible duplicate" problem. Now that real payments arrive via
 * import, these synthetic rows are pure noise — delete them so a recurring
 * bucket's allocation accumulates and only real payments draw it down.
 *
 * Scope: rows with isAutoGenerated === true. By default we KEEP user-overridden
 * ones (the user edited that row, so it stands in for a real payment) — pass
 * includeOverridden: true to remove those too.
 *
 * DRY RUN by default. Usage (Convex dashboard / CLI):
 *   npx convex run recurringCleanup:removeAutoPays '{"userId":"<id>"}'
 *   npx convex run recurringCleanup:removeAutoPays '{"userId":"<id>","apply":true}'
 */

import { v } from 'convex/values';
import { internalMutation } from './_generated/server';

export const removeAutoPays = internalMutation({
  args: {
    userId: v.id('users'),
    apply: v.optional(v.boolean()),
    includeOverridden: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const apply = args.apply === true;

    const buckets = await ctx.db
      .query('buckets')
      .withIndex('by_user', q => q.eq('userId', args.userId))
      .collect();

    const perBucket: Array<{
      bucketId: string;
      bucketName: string;
      count: number;
      total: number;
      keptOverridden: number;
    }> = [];
    let totalRemoved = 0;
    let totalAmount = 0;

    for (const bucket of buckets) {
      const autoRows = await ctx.db
        .query('expenses')
        .withIndex('by_bucket', q => q.eq('bucketId', bucket._id))
        .filter(q => q.eq(q.field('isAutoGenerated'), true))
        .collect();

      let count = 0;
      let total = 0;
      let keptOverridden = 0;
      for (const row of autoRows) {
        if (row.userOverridden && !args.includeOverridden) {
          keptOverridden += 1;
          continue;
        }
        count += 1;
        total += row.amount;
        if (apply) await ctx.db.delete(row._id);
      }

      if (count > 0 || keptOverridden > 0) {
        perBucket.push({
          bucketId: bucket._id,
          bucketName: bucket.name,
          count,
          total: Math.round(total * 100) / 100,
          keptOverridden,
        });
      }
      totalRemoved += count;
      totalAmount += total;
    }

    return {
      apply,
      totalRemoved,
      totalAmount: Math.round(totalAmount * 100) / 100,
      perBucket,
    };
  },
});
