import { v } from "convex/values";
import { internalMutation } from "./_generated/server";
import { merchantKey } from "./lib/merchantKey";

// One-off (Oct 2026): the accounts in the check-in now track investments, so
// the old IBKR and Endowus cups go, and so does a stray test cup ("fr").
// A transfer into IBKR filed to the IBKR cup is not spending: remove the
// spend (its "put in" is already on the Stocks (IBKR) account) and send
// future IBKR transfers to that account. dryRun first.

const RETIRE = ["IBKR", "Endowus", "fr"];

export const run = internalMutation({
  args: { userId: v.id("users"), dryRun: v.boolean() },
  handler: async (ctx, { userId, dryRun }) => {
    const log: string[] = [];
    const buckets = (await ctx.db.query("buckets").withIndex("by_user", (q) => q.eq("userId", userId)).collect()).filter((b) => b.isActive);
    const accounts = await ctx.db.query("accounts").withIndex("by_user", (q) => q.eq("userId", userId)).collect();
    const stocks = accounts.find((a) => a.isActive && a.name === "Stocks (IBKR)");

    for (const name of RETIRE) {
      const b = buckets.find((x) => x.name === name);
      if (!b) continue;
      log.push(`retire cup "${name}"`);
      if (name === "IBKR") {
        const spends = await ctx.db.query("expenses").withIndex("by_bucket", (q) => q.eq("bucketId", b._id)).collect();
        for (const e of spends.filter((e) => !e.isAutoGenerated && /ibkr/i.test(e.note ?? ""))) {
          log.push(`  remove spend $${e.amount} on ${new Date(e.date).toISOString().slice(0, 10)} (${e.note})`);
          if (!dryRun) await ctx.db.delete(e._id);
        }
      }
      if (!dryRun) await ctx.db.patch(b._id, { isActive: false });
    }

    if (stocks) {
      const rule = await ctx.db
        .query("merchantRules")
        .withIndex("by_user_key", (q) => q.eq("userId", userId).eq("key", merchantKey("Ibkr")))
        .first();
      if (rule && rule.accountId !== stocks._id) {
        log.push(`IBKR transfers now go to "${stocks.name}"`);
        if (!dryRun) await ctx.db.patch(rule._id, { bucketId: undefined, accountId: stocks._id, updatedAt: Date.now() });
      }
    }
    return { dryRun, changes: log };
  },
});
