import { useSyncExternalStore } from 'react';
import type { Expense } from '../types';

// A day in ms — the window for the "same-day re-log" case.
export const SAME_DAY_MS = 24 * 60 * 60 * 1000;

type DupExpense = Pick<Expense, '_id' | 'amount' | 'date'> & {
  isAutoGenerated?: boolean;
};

const sameMonth = (a: number, b: number): boolean => {
  const da = new Date(a);
  const db = new Date(b);
  return da.getFullYear() === db.getFullYear() && da.getMonth() === db.getMonth();
};

/**
 * Ids of expenses that look like duplicates of another expense in the same set.
 *
 * Precise signal (avoids flagging normal repeat spends like two $2 transit
 * fares a few days apart): a same-amount pair is a duplicate only when EITHER
 *  - one of them is the auto-generated recurring payment and they're in the
 *    same month (the auto-pay + a manually-logged / imported copy), OR
 *  - they fall on effectively the same day (an accidental double-entry).
 *
 * Pass expenses for a SINGLE bucket (the caller scopes by bucket). `dismissed`
 * holds ids the user marked "not a duplicate" — a pair is skipped entirely if
 * either member was dismissed, so confirming one row as fine clears its pill
 * (and its partner's, since they no longer have an active match).
 */
export function findDuplicateExpenseIds(
  expenses: DupExpense[],
  opts: { sameDayMs?: number; dismissed?: Set<string> } = {},
): Set<string> {
  const sameDayMs = opts.sameDayMs ?? SAME_DAY_MS;
  const dismissed = opts.dismissed;
  const dupes = new Set<string>();
  for (let i = 0; i < expenses.length; i++) {
    for (let j = i + 1; j < expenses.length; j++) {
      const a = expenses[i];
      const b = expenses[j];
      if (dismissed && (dismissed.has(a._id) || dismissed.has(b._id))) continue;
      if (Math.abs(a.amount - b.amount) >= 0.01) continue;

      const oneIsAutoPay = !!(a.isAutoGenerated || b.isAutoGenerated);
      const recurringCopy = oneIsAutoPay && sameMonth(a.date, b.date);
      const sameDayRelog = Math.abs(a.date - b.date) <= sameDayMs;

      if (recurringCopy || sameDayRelog) {
        dupes.add(a._id);
        dupes.add(b._id);
      }
    }
  }
  return dupes;
}

// "Not a duplicate" dismissals, persisted locally (mirrors the dismissed-
// insights pattern). Keyed by expense id; an id here is never flagged.
//
// Backed by a tiny reactive store so every screen stays in sync: dismissing a
// pill in the bucket detail must immediately drop the ⚠ badge on the overview
// cup. We cache the snapshot Set and only rebuild it on a write, so
// useSyncExternalStore sees a stable reference between changes.
const DISMISS_KEY = 'buckets_dismissed_duplicates';

let snapshot: Set<string> | null = null;
const listeners = new Set<() => void>();

function load(): Set<string> {
  try {
    const raw = localStorage.getItem(DISMISS_KEY);
    return raw ? new Set<string>(JSON.parse(raw)) : new Set<string>();
  } catch {
    return new Set<string>();
  }
}

export function getDismissedDuplicates(): Set<string> {
  if (!snapshot) snapshot = load();
  return snapshot;
}

export function dismissDuplicate(expenseId: string): void {
  try {
    const s = new Set(getDismissedDuplicates());
    s.add(expenseId);
    localStorage.setItem(DISMISS_KEY, JSON.stringify([...s]));
  } catch {
    // ignore storage failures — flag just stays visible
  }
  snapshot = load(); // new reference → subscribers re-render
  listeners.forEach((l) => l());
}

function subscribe(cb: () => void): () => void {
  listeners.add(cb);
  return () => listeners.delete(cb);
}

/**
 * React hook: current dismissed-duplicate ids, re-rendering the caller whenever
 * a dismissal happens anywhere in the app.
 */
export function useDismissedDuplicates(): Set<string> {
  return useSyncExternalStore(subscribe, getDismissedDuplicates, getDismissedDuplicates);
}
