// Read-only: count the auto-generated "recurring payment" rows the cleanup
// would remove, per bucket. Deploys nothing, writes nothing.
//   node scripts/autoPayImpact.mjs <userId>

import { ConvexHttpClient } from 'convex/browser';
const URL = 'https://polite-gull-255.convex.cloud';
const userId = process.argv[2];
if (!userId) { console.error('usage: autoPayImpact.mjs <userId>'); process.exit(1); }
const client = new ConvexHttpClient(URL);
const m = (n) => `$${(n ?? 0).toFixed(2)}`;

const main = async () => {
  const buckets = await client.query('buckets:getByUser', { userId });
  let totalRows = 0, totalAmt = 0;
  console.log('\nAuto-generated rows the cleanup would remove:\n');
  for (const b of buckets) {
    const exp = await client.query('expenses:getByBucket', { bucketId: b._id });
    const auto = exp.filter((e) => e.isAutoGenerated && !e.userOverridden);
    const overridden = exp.filter((e) => e.isAutoGenerated && e.userOverridden);
    if (auto.length || overridden.length) {
      const sum = auto.reduce((s, e) => s + e.amount, 0);
      totalRows += auto.length; totalAmt += sum;
      console.log(`  ${b.name.padEnd(20)} remove ${String(auto.length).padStart(3)} rows (${m(sum)})` +
        (overridden.length ? `  [keep ${overridden.length} user-edited]` : ''));
    }
  }
  console.log(`\n  TOTAL: ${totalRows} rows, ${m(totalAmt)} of synthetic "spend" removed`);
  console.log('  (read-only — nothing changed)\n');
};
main().catch((e) => { console.error('FAILED:', e.message); process.exit(1); });
