// Read-only: compare each transaction's `date` (shown/sorted) vs `createdAt`
// (entry time) for one bucket, to see if sorting by date matches intent.
//   node scripts/inspectTxns.mjs <userId> <bucketNameSubstring>

import { ConvexHttpClient } from 'convex/browser';
const URL = 'https://polite-gull-255.convex.cloud';
const [userId, namePart] = [process.argv[2], (process.argv[3] || '').toLowerCase()];
if (!userId) { console.error('usage: inspectTxns.mjs <userId> <bucketName>'); process.exit(1); }
const client = new ConvexHttpClient(URL);
const d = (ts) => new Date(ts).toISOString().slice(0, 16).replace('T', ' ');

const main = async () => {
  const buckets = await client.query('buckets:getByUser', { userId });
  const bucket = buckets.find((b) => b.name.toLowerCase().includes(namePart)) || buckets[0];
  console.log(`\nbucket: ${bucket.name} (${bucket.bucketMode})\n`);
  const exp = await client.query('expenses:getByBucket', { bucketId: bucket._id });
  console.log(`${exp.length} expenses. Columns: date | createdAt | note | auto?`);
  console.log('— as returned by query (creation order) —');
  for (const e of exp.slice(0, 14)) {
    const sameMin = Math.abs(e.date - e.createdAt) < 60000;
    console.log(`  date ${d(e.date)} | created ${d(e.createdAt)} ${sameMin ? '⟵ SAME as entry' : ''} | ${e.note} ${e.isAutoGenerated ? '[auto]' : ''}`);
  }
  console.log('\n— sorted by date desc (what the fix does) —');
  for (const e of [...exp].sort((a, b) => b.date - a.date).slice(0, 14)) {
    console.log(`  ${d(e.date)} | ${e.note}`);
  }
  console.log('');
};
main().catch((e) => { console.error('FAILED:', e.message); process.exit(1); });
