// Verify the deployed recurringSync is the no-op (creates/deletes nothing).
// Counts auto-generated rows before and after one sync call, and prints the
// returned diff. If the OLD code were live, the diff would be non-empty and
// counts could change; the no-op returns {diff: []} and leaves counts identical.
//   node scripts/verifySync.mjs <userId>

import { ConvexHttpClient } from 'convex/browser';
const URL = 'https://polite-gull-255.convex.cloud';
const userId = process.argv[2];
if (!userId) { console.error('usage: verifySync.mjs <userId>'); process.exit(1); }
const client = new ConvexHttpClient(URL);

const now = new Date();
const month = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;

const countAuto = async () => {
  const buckets = await client.query('buckets:getByUser', { userId });
  let total = 0, thisMonth = 0;
  for (const b of buckets) {
    const exp = await client.query('expenses:getByBucket', { bucketId: b._id });
    for (const e of exp) {
      if (e.isAutoGenerated) {
        total += 1;
        if (e.autoGeneratedForMonth === month) thisMonth += 1;
      }
    }
  }
  return { total, thisMonth };
};

const main = async () => {
  console.log(`\nMonth: ${month}\n`);
  const before = await countAuto();
  console.log(`auto-generated rows BEFORE: ${before.total} total, ${before.thisMonth} for this month`);

  const res = await client.mutation('recurringSync:syncRecurringExpensesForMonth', { userId, month });
  console.log(`\nsync returned diff: ${JSON.stringify(res.diff)}  (empty [] = no-op)`);

  const after = await countAuto();
  console.log(`\nauto-generated rows AFTER:  ${after.total} total, ${after.thisMonth} for this month`);

  const unchanged = before.total === after.total && before.thisMonth === after.thisMonth;
  console.log(`\n${res.diff.length === 0 && unchanged ? '✅ VERIFIED: no-op active — nothing created or deleted.' : '⚠ UNEXPECTED: diff non-empty or counts changed!'}\n`);
};
main().catch((e) => { console.error('FAILED:', e.message); process.exit(1); });
