import { findDuplicateExpenseIds } from '../src/utils/duplicates';

const day = (y: number, m: number, d: number) => new Date(y, m - 1, d).getTime();

describe('findDuplicateExpenseIds — precise signal', () => {
  it('does NOT flag normal repeat spends (transit fares) a few days apart', () => {
    const out = findDuplicateExpenseIds([
      { _id: 'a', amount: 2.2, date: day(2026, 3, 26) },
      { _id: 'b', amount: 2.2, date: day(2026, 3, 30) },
    ]);
    expect(out.size).toBe(0);
  });

  it('flags auto-pay + a manual copy in the same month (different days)', () => {
    const out = findDuplicateExpenseIds([
      { _id: 'auto', amount: 250, date: day(2026, 6, 1), isAutoGenerated: true },
      { _id: 'manual', amount: 250, date: day(2026, 6, 19) },
    ]);
    expect(out).toEqual(new Set(['auto', 'manual']));
  });

  it('does NOT flag auto-pay vs a copy in a DIFFERENT month', () => {
    const out = findDuplicateExpenseIds([
      { _id: 'auto', amount: 250, date: day(2026, 6, 1), isAutoGenerated: true },
      { _id: 'other', amount: 250, date: day(2026, 5, 19) },
    ]);
    expect(out.size).toBe(0);
  });

  it('flags two identical entries on the same day (accidental re-log)', () => {
    const out = findDuplicateExpenseIds([
      { _id: 'x', amount: 1100, date: day(2026, 6, 19) },
      { _id: 'y', amount: 1100, date: day(2026, 6, 19) },
    ]);
    expect(out).toEqual(new Set(['x', 'y']));
  });

  it('respects dismissals — clearing one clears the pair', () => {
    const rows = [
      { _id: 'auto', amount: 250, date: day(2026, 6, 1), isAutoGenerated: true },
      { _id: 'manual', amount: 250, date: day(2026, 6, 19) },
    ];
    const out = findDuplicateExpenseIds(rows, { dismissed: new Set(['manual']) });
    expect(out.size).toBe(0);
  });

  it('different amounts are never duplicates', () => {
    const out = findDuplicateExpenseIds([
      { _id: 'a', amount: 250, date: day(2026, 6, 19) },
      { _id: 'b', amount: 251, date: day(2026, 6, 19) },
    ]);
    expect(out.size).toBe(0);
  });
});
